name: "Running tests: style, mypy"

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Style, mypy
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: pip install -e .[dev]
    - name: Check black
      run: python -m black --check --diff --color .
    - name: Check isort
      run: python -m isort --check --diff .
    - name: Check flake8
      run: python -m flake8 .
    - name: Check mypy
      run: python -m mypy .
